spring:
  application:
    name: majorYard
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  cloud:
    aws:
      credentials:
        access-key: AKIA5FTZBMBQWGRD626H
        secret-key: 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
      s3:
        bucket: majoryardbucket
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/majorYard?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 12345555


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true  # SQL 출력 여부
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # 사용할 SQL Dialect
        format_sql: true # SQL 포맷팅 여부


jwt:
  header: Authorization  # JWT 토큰을 저장할 헤더 이름
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400	# 초 # 토큰 유효 시간 (초 단위)


logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

