insert into User (user_no, department_no, user_name, nickName, gender) values (1, 1, '김산학', '산학이', 'MALE');
insert into User (user_no, department_no, user_name, nickName, gender) values (2, 1, '팽유영', '별팽이', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (3, 1, '김묘수', '묭묭', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (4, 1, '남궁진혁', '온이', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (5, 1, '박산', '학산이', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (6, 1, '오진이', '오목눈이', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (7, 1, '이해미', '할미', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (8, 1, '김영미', '영이', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (9, 1, '봉희수', '붕붕이', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (10, 1, '오장현', '오장육부', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (11, 2, '이묘주', '렐이', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (12, 2, 'Sally', '샘이', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (13, 2, '김한나', '구름', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (14, 2, '최고진', '최고에요', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (15, 2, '한소희', '별이', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (16, 2, '신우주', '사모예드', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (17, 2, '변고진', '뻐꾸기', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (18, 2, '진현정', '징징이', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (19, 2, '한장연', '산학최고', 'MALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (20, 2, '이이담', '산학짱', 'FEMALE');
insert into User (User.user_no, User.department_no, User.user_name, User.nickName, User.gender) values (21, 2, 'issue_alarm', '이슈 알리미', 'FEMALE');

commit;