insert into User (user_name, nickName, gender) values ('Papagena', 'Derham', 'FEMALE');
insert into User (user_name, nickName, gender) values ('Haily', 'Juanes', 'MALE');
insert into User (user_name, nickName, gender) values ('Loydie', 'Dougharty', 'MALE');
insert into User (user_name, nickName, gender) values ('Susanne', 'Paslow', 'FEMALE');
insert into User (user_name, nickName, gender) values ('Conroy', 'Indgs', 'MALE');
insert into User (user_name, nickName, gender) values ('Orrin', 'Guilliatt', 'MALE');
insert into User (user_name, nickName, gender) values ('Stevy', 'Barajas', 'MALE');
insert into User (user_name, nickName, gender) values ('Jessy', 'Simyson', 'FEMALE');
insert into User (user_name, nickName, gender) values ('Joaquin', 'Gormally', 'MALE');
insert into User (user_name, nickName, gender) values ('Woodie', 'Heball', 'MALE');
insert into User (user_name, nickName, gender) values ('Pengs', 'Wallow', 'MALE');
insert into User (user_name, nickName, gender) values ('Sally', 'Ben', 'MALE');
insert into User (user_name, nickName, gender) values ('Maquin', 'Sunhill', 'MALE');
insert into User (user_name, nickName, gender) values ('Daniel', 'Fisher', 'FEMALE');
insert into User (user_name, nickName, gender) values ('Sussie', 'Piere', 'MALE');
insert into User (user_name, nickName, gender) values ('Welham', 'Boomer', 'FEMALE');
insert into User (user_name, nickName, gender) values ('Lucas', 'Sam', 'FEMALE');
insert into User (user_name, nickName, gender) values ('Pompom', 'Susanna', 'FEMALE');
insert into User (user_name, nickName, gender) values ('Jaegyeong', 'Smith', 'MALE');
insert into User (user_name, nickName, gender) values ('Kitty', 'Robin', 'FEMALE');

commit;